version: '3.8'

# Development configuration with hot reload
services:
  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama-dev
    ports:
      - "11434:11434"
    volumes:
      - ollama_data_dev:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        # Lighter resource limits for development
        limits:
          cpus: '2'
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - rag-network-dev

  rag-agent-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rag-agent-dev
    ports:
      - "8000:8000"
    volumes:
      # Mount source code for hot reload
      - ./app:/app/app
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./main.py:/app/main.py
      - ./run_api.py:/app/run_api.py
      # Persist data
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_TO_FILE=true
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rag-network-dev
    command: python main.py
    # Alternative command for API mode:
    # command: python run_api.py
    stdin_open: true
    tty: true

volumes:
  ollama_data_dev:
    driver: local

networks:
  rag-network-dev:
    driver: bridge