"""Add registration_attempts table

Revision ID: 19a624af8e31
Revises: 006d6d1ecc47
Create Date: 2025-10-20 16:54:19.910591+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a624af8e31'
down_revision = '006d6d1ecc47'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_error_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registration_attempts_client_id'), 'registration_attempts', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_attempts_client_id'), table_name='registration_attempts')
    op.drop_table('registration_attempts')
    # ### end Alembic commands ###