name: Keep Render Service Alive

on:
  schedule:
    # Run every 14 minutes to prevent Render free tier spin-down (15min timeout)
    # Note: GitHub Actions schedule has ~3-10 min delay, so we use 14 min to be safe
    - cron: '*/14 * * * *'

  workflow_dispatch: # Allows manual trigger from Actions tab for testing

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping health endpoint
        run: |
          echo "🔔 Pinging service at $(date)"
          
          # Replace with your actual Render service URL
          SERVICE_URL=" https://api.vibecoder.buzz/health"
          
          response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 180 $SERVICE_URL)
          
          if [ $response -eq 200 ]; then
            echo "✅ Service is alive (HTTP $response)"
          elif [ $response -eq 000 ]; then
            echo "⏳ Service is cold starting (this is normal for first ping after spin-down)"
            echo "Waiting 30s and retrying..."
            sleep 30
            response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 180 $SERVICE_URL)
            if [ $response -eq 200 ]; then
              echo "✅ Service responded after cold start (HTTP $response)"
            else
              echo "⚠️ Service still not responding: HTTP $response"
              exit 1
            fi
          else
            echo "⚠️ Unexpected response: HTTP $response"
            exit 1
          fi

      - name: Log completion
        if: always()
        run: echo "✅ Keep-alive ping completed at $(date)"